### ISSUE TITLE
[Suggestion] Queue Time Tracker

### ISSUE THREAD

**Issue by CyanideX** [bakkesmodorg/BakkesMod2-Plugins#8]
Track how long you spend in queue waiting to find a match.

**Comment by eren-kemer** [comment]
@CyanideX You might want to take a look at a plugin i've just recently developed.
https://github.com/eren-kemer/QueueTracker

It is currently pending approval on bakkesplugins.com so it should be available to install in the next few days.
I personally don't think this should/could be a default plugin though.

**Comment by eren-kemer** [comment]
On a sidenote: the plugin has been verified and is up for grabs at https://bakkesplugins.com/plugins/view/186

**Comment by CyanideX** [comment]
Fantastic! Thank you so much for making this. I'm looking forward to the updates to track average and total queue times! 🙂
